Feature/mc 62
dotval/menta_clone pull request #11
Opened 2020-10-25 06:01 UTC by tadashimasuda

bcrypt で暗号化しました。

2020-11-28 02:33 UTC, tadashimasuda commented
bcryptを取り入れた影響で後々package.jsonでコンフリクトなどが出て来るかもしれません。

2020-12-02 19:42 UTC, shimonosatoru requested changes
微調整だけ！お願いします！

2020-12-02 19:42 UTC, shimonosatoru commented on api/controllers/usersController.js
> +var rounds = bcrypt.genSaltSync(saltRounds);
constで！

2020-12-02 19:42 UTC, shimonosatoru commented on api/controllers/usersController.js
> +var rounds = bcrypt.genSaltSync(saltRounds);
特に`saltRounds `は定数なので`SALT_ROUNDS`のほうがわかりやすいかも

2020-12-03 12:11 UTC, tadashimasuda commented on api/controllers/usersController.js
> +var rounds = bcrypt.genSaltSync(saltRounds);
修正しました。

2020-12-04 07:43 UTC, shimonosatoru approved these changes
LGTM!

2020-12-04 12:19 UTC, merged